import { StyleSheet } from 'react-native';

const styles = (wp: any, hp: any) =>
  StyleSheet.create({
    background: {
      flex: 1,
      width: '100%',
      height: '100%',
    },
    container: {
      flex: 1,
      paddingHorizontal: wp(5),
      paddingTop: hp(4),
      alignItems: 'center',
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      marginBottom: hp(2),
    },
    backButton: {
      marginRight: wp(2),
      marginLeft: wp(-2),
    },
    headerTitle: {
      fontSize: wp(5),
      fontFamily: 'Poppins-Bold',
      color: '#222',
    },
    logoContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FFE6C7',
      borderRadius: wp(6),
      width: wp(26),
      height: wp(23),
      marginBottom: hp(2),
      marginTop: hp(2.5),
    },
    logo: {
      width: wp(20),
      height: wp(20),
      resizeMode: 'contain',
    },
    title: {
      fontSize: 20,
      fontFamily: 'Quicksand-SemiBold',
      color: '#000',
      marginTop: hp(0),
      marginBottom: hp(1),
      textAlign: 'center',
    },
    subtitle: {
      fontSize: 15,
      fontFamily: 'Quicksand-Regular',
      color: '#000',
      textAlign: 'center',
      marginBottom: hp(3),
      marginHorizontal: wp(12),
    },
    cardFormContainer: {
      backgroundColor: '#fff',
      borderRadius: wp(4),
      width: '100%',
      padding: wp(6),
      paddingBottom: hp(1.5),
      marginBottom: hp(4),
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    cardNumberInput: {
      fontSize: 22,
      fontFamily: 'Quicksand-SemiBold',
      color: '#000',
      marginBottom: hp(2),
      paddingBottom: hp(1),
    },
    cardFormRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: hp(1),
    },
    expiryInput: {
      flex: 1,
      fontSize: 22,
      fontFamily: 'Quicksand-SemiBold',
      color: '#000',
      paddingVertical: hp(1),
    },
    verticalDivider: {
      width: 1,
      height: '100%',
      backgroundColor: '#E0E0E0',
      marginHorizontal: wp(2),
      marginLeft: wp(20),
    },
    cvvInput: {
      flex: 1,
      fontSize: 22,
      fontFamily: 'Quicksand-SemiBold',
      color: '#000',
      paddingVertical: hp(1),
      textAlign: 'center',
      marginLeft: wp(5),
    },
    saveButton: {
      backgroundColor: '#264734',
      borderRadius: wp(10),
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      height: hp(7),
      alignSelf: 'center',
      marginTop: hp(2),
      marginBottom: hp(2),
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 2,
    },
    saveButtonText: {
      color: '#FFF',
      fontSize: wp(5),
      fontFamily: 'Poppins-Bold',
    },
    cardLabelRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: hp(0),
    },
    cardLabel: {
      fontSize: 13,
      fontFamily: 'Poppins-Bold',
      color: '#000',
      marginLeft: wp(2.2),
    },
    cardLogosRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    cardLogo: {
      width: wp(26),
      height: wp(9),
      resizeMode: 'cover',
      marginTop: wp(-3),
     marginRight: wp(-5),
    },
    cardDivider: {
      width: '100%',
      height: 1,
      backgroundColor: '#E0E0E0',
      marginVertical: hp(1),
      marginTop: hp(-0.3),
    },
    cardFieldCol: {
      flex: 1,
      alignItems: 'flex-start',
    },
    cardFieldLabel: {
      fontSize: 13,
      fontFamily: 'Poppins-Bold',
      color: '#000',
      marginBottom: hp(0.5),
      marginLeft: wp(3),
    },
  });

export default styles; 