// import { Dimensions } from 'react-native';
import { StyleSheet } from 'react-native';
// const screenWidth = Dimensions.get('window').width;
// const isTablet = screenWidth > 768;

// const gridColumn = isTablet ? 4 : 4;
const styles = (wp: any, hp: any) =>
  StyleSheet.create({
    mainContainer: {
      flex: 1,
      position: 'relative',
    },
    menuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: hp(1),
    },
    menuText: {
      marginLeft: wp(2),
      fontSize: wp(3.8),
      color: '#000',
    },

    bgimg: {
      flex: 1,
      resizeMode: 'cover',
    },
    mainScrollView: {
      flex: 1,
    },
    innercontainer: {
      borderRadius: 15,
      paddingHorizontal: wp(1.2),
      paddingTop: hp(2),
      paddingBottom: hp(10),
      marginTop: hp(2),
    },
    container: {
      flex: 1,
      padding: 16,
      marginTop: hp(3),
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: hp(2),
    },
    logo: {
      width: wp(40),
      height: hp(6),
      resizeMode: 'contain',
    },
    headerText: {
      fontSize: wp(3),
      marginTop: hp(0),
      color: '#000',
      marginLeft: hp(1),
      fontFamily: 'Quicksand-SemiBold',
    },
    headerIcons: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    bellIcon: {
      width: wp(6),
      height: wp(6),
      marginRight: wp(3),
    },
    userIcon: {
      width: wp(8),
      height: wp(8),
      borderRadius: wp(4),
    },
    featureRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      flexWrap: 'wrap',
      marginBottom: hp(3),
      marginTop: hp(1.5),
      marginHorizontal: hp(2.4),
    },
    featureBtn: {
      width: wp(19),
      height: wp(21),
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: hp(2),
    },
    featureIcon: {
      width: wp(15),
      height: wp(15),
      marginBottom: hp(1),
      resizeMode: 'cover',
    },
    // featureText: {
    //   fontSize: wp(2.8),
    //   textAlign: 'center',
    //   fontFamily: 'Poppins-SemiBold',
    // },
    servicesContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: hp(3),
      marginTop: hp(1.5),
      paddingHorizontal: wp(2),
      gap: wp(2),
    },
    serviceCard: {
      width: wp(22),
      height: wp(28),
      borderRadius: wp(3),
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: '#264734',
      position: 'relative',
    },
    serviceCardIcon: {
      width: wp(22),
      height: wp(28),
      borderRadius: wp(0),
      alignItems: 'center',
      justifyContent: 'center',
      padding: wp(2),
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    serviceImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
      borderRadius: wp(3),
    },
    serviceIcon: {
      width: wp(12),
      height: wp(12),
      resizeMode: 'cover',
      marginBottom: hp(0.5),
      tintColor: '#264734',
    },
    serviceOverlay: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      paddingVertical: hp(1),
      paddingHorizontal: wp(1.5),
      alignItems: 'center',
      borderBottomLeftRadius: wp(3),
      borderBottomRightRadius: wp(3),
    },
    serviceText: {
      fontSize: wp(2.8),
      color: '#fff',
      fontFamily: 'Poppins-SemiBold',
      textAlign: 'center',
      lineHeight: wp(3.5),
    },
    serviceTextIcon: {
      fontSize: wp(2.8),
      color: '#264734',
      fontFamily: 'Poppins-SemiBold',
      textAlign: 'center',
      lineHeight: wp(3.5),
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: hp(1),
    },
    sectionTitle: {
      fontSize: wp(5),
      fontWeight: '700',
      fontFamily: 'Poppins-Bold',
    },
    arrow: {
      fontSize: wp(10),
      color: '#000',
    },
    journeyCard: {
      width: wp(50),
      backgroundColor: '#fff',
      borderRadius: wp(4),
      padding: wp(3),
      marginRight: wp(3),
      marginBottom: hp(2),
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    journeyImg: {
      width: '100%',
      height: hp(15),
      borderRadius: wp(0),
      marginBottom: hp(2),
      resizeMode: 'cover',
    },
    journeyContent: {
      flex: 1,
      justifyContent: 'space-between',
    },
    journeyTitle: {
      fontSize: wp(4.5),
      marginBottom: hp(1),
      fontFamily: 'Poppins-Bold',
      color: '#000',
      lineHeight: wp(5.5),
    },
    journeyText: {
      fontSize: wp(3.5),
      color: '#6B7280',
      marginBottom: hp(0),
      fontFamily: 'Poppins-Regular',
      lineHeight: wp(4.5),
    },
    detailsBtn: {
      backgroundColor: '#264734',
      paddingVertical: hp(1),
      borderRadius: wp(6),
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    detailsText: {
      color: '#fff',
      fontSize: wp(3.5),
      fontFamily: 'Poppins-SemiBold',
    },
    eventCard: {
      width: wp(55),
      backgroundColor: '#fff',
      borderRadius: wp(3),
      padding: wp(3),
      marginBottom: hp(2),
    },
    eventImg: {
      width: '100%',
      height: hp(15),
      borderRadius: wp(2),
      marginRight: wp(4),
      marginBottom: hp(1),
    },
    eventContent: {
      flex: 1,
    },
    tagsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: hp(1),
      justifyContent: 'space-between',
    },
    fromTag: {
      backgroundColor: '#264734',
      paddingHorizontal: wp(1.8),
      paddingVertical: wp(0.4),
      borderRadius: wp(5),
      marginRight: wp(2),
    },
    typeTag: {
      paddingVertical: wp(0),
      borderRadius: wp(5),
    },
    tagText: {
      fontSize: wp(3),
      color: '#fff',
      fontFamily: 'Poppins-Bold',
    },
    eventTitle: {
      fontSize: wp(3.5),
      fontFamily: 'Poppins-SemiBold',
      marginBottom: hp(0.5),
      marginRight: wp(-3),
    },
    eventDesc: {
      fontSize: wp(3.1),
      color: '#979797',
      fontFamily: 'Poppins-Medium',
    },
    outercontainer: {
      position: 'absolute',
      bottom: hp(8),
      right: wp(4),
      flexDirection: 'column',
      alignItems: 'center',
      zIndex: 1000,
    },
    staticFloatingContainer: {
      position: 'absolute',
      bottom: hp(8),
      right: wp(4),
      flexDirection: 'column',
      alignItems: 'center',
      zIndex: 1000,
    },
    fab: {
      width: wp(17),
      height: wp(17),
      borderRadius: wp(10),
      backgroundColor: '#003300',
      borderWidth: 1,
      borderColor: '#F97316',
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 5,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
    },
    icon: {
      width: wp(8),
      height: wp(8),
      resizeMode: 'contain',
    },
    textContainer: {
      marginLeft: wp(2),
      paddingHorizontal: wp(3),
      paddingVertical: hp(0.8),
    },
    text: {
      fontSize: wp(3.5),
      color: '#000',
    },

    feedCard: {
      backgroundColor: '#fff',
      padding: wp(4),
      borderRadius: wp(3),
      marginBottom: hp(2),
      borderWidth: 1,
    },
    feedHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: hp(1),
    },
    feedAvatar: {
      width: wp(8),
      height: wp(8),
      borderRadius: wp(4),
      marginRight: wp(2),
    },
    feedUser: {
      fontWeight: '600',
      fontSize: wp(4),
    },
    feedText: {
      fontSize: wp(3.5),
      color: '#333',
      marginVertical: hp(1),
    },
    feedStats: {
      flexDirection: 'row',
      gap: 0,
      paddingTop: hp(1),
    },

    statItem: {
      flexDirection: 'row',
      alignItems: 'center',
      marginRight: wp(4),
    },
    feedicon: {
      width: wp(5),
      height: wp(5),
      resizeMode: 'contain',
      marginRight: wp(1),
    },
    statText: {
      fontSize: wp(3.2),
      color: '#000',
    },
    scrollContent: {
      flexGrow: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: hp(10),
    },
    backButton: {
      top: hp(3),
      width: wp(10),
      height: wp(10),
      justifyContent: 'center',
      alignItems: 'center',
    },
    title: {
      fontSize: wp(5),
      fontFamily: 'Poppins-Bold',
      marginTop: hp(-1),
      marginRight: hp(10),
      textAlign: 'center',
    },
    grid: {
      flexDirection: 'row',
      paddingHorizontal: wp(4),
      paddingVertical: hp(1),
      gap: wp(3),
    },
    featureBox: {
      width: wp(21),
      height: wp(26),
      borderRadius: wp(1.5),
      overflow: 'hidden',
      borderWidth: 0,
      borderColor: '#264734',
      position: 'relative',
      marginBottom: hp(-1),
    },
    featureOverlay: {
      position: 'absolute',
      bottom: 5,
      left: 0,
      right: 0,
      paddingVertical: hp(1),
      paddingHorizontal: wp(1),
      borderBottomRightRadius: wp(1),
      borderBottomLeftRadius: wp(1),
      alignItems: 'center',
      justifyContent: 'center',
    },
    featureImage: {
      width: '100%',
      height: '100%',
      borderRadius: wp(0),
      resizeMode: 'contain',
    },
    featureText: {
      fontSize: 8.5,
      textAlign: 'center',
      color: '#fff',
      fontFamily: 'Poppins-SemiBold',
      lineHeight: wp(3.2),
      fontWeight: '600',
    },
  });

export default styles;
