import { StyleSheet } from 'react-native';

const styles = (wp: any, hp: any) =>
  StyleSheet.create({
    background: {
      flex: 1,
      width: '100%',
      height: '100%',
    },
    container: {
      flex: 1,
      alignItems: 'center',
      paddingHorizontal: wp(7.5),
      paddingTop: hp(3),
    },
    logo: {
      width: wp(35),
      height: hp(7),
      resizeMode: 'contain',
      marginBottom: hp(2),
      marginTop: hp(2),
    },
    header: {
      fontSize: 26,
      fontFamily: 'Urbanist-SemiBold',
      color: '#222',
      textAlign: 'center',
      marginBottom: hp(1),
    },
    subheader: {
      fontSize: 14,
      fontFamily: 'Montserrat-Medium',
      color: '#222',
      textAlign: 'center',
      marginBottom: hp(3),
      lineHeight: 24,
      width: '100%',
    },
    label: {
      fontSize: wp(3.5),
      fontFamily: 'Poppins-Medium',
      color: '#222',
      marginBottom: hp(0.5),
      marginTop: hp(1.5),
      alignSelf: 'flex-start',
      marginLeft: wp(0.8),
    },
    inputContainer: {
      width: '95%',
      marginBottom: hp(1),
    },
    input: {
      width: '100%',
      height: hp(6.5),
      borderRadius: wp(10),
      backgroundColor: '#F7F8FA',
      paddingHorizontal: wp(5),
      fontSize: wp(4),
      fontFamily: 'Montserrat-Regular',
      color: '#222',
      borderWidth: 1,
      borderColor: '#E0E0E0',
    },
    select: {
      width: '95%',
      height: hp(6.5),
      borderRadius: wp(10),
      backgroundColor: '#F7F8FA',
      paddingHorizontal: wp(5),
      fontSize: wp(4),
      fontFamily: 'Montserrat-Regular',
      color: '#888',
      borderWidth: 1,
      borderColor: '#E0E0E0',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    selectIcon: {
      marginLeft: wp(2),
    },
    textarea: {
      width: '95%',
      minHeight: hp(6.5),
      borderRadius: wp(10),
      backgroundColor: '#F7F8FA',
      paddingHorizontal: wp(5),
      fontSize: wp(4),
      fontFamily: 'Montserrat-Regular',
      color: '#222',
      borderWidth: 1,
      borderColor: '#E0E0E0',
      textAlignVertical: 'top',
      marginBottom: hp(1),
    },
    checkboxRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: hp(2),
      marginBottom: hp(2),
      alignSelf: 'flex-start',
    },
    checkbox: {
      width: wp(6),
      height: wp(6),
      borderRadius: wp(1.5),
      borderWidth: 2,
      borderColor: '#264734',
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: wp(2),
    },
    checkboxChecked: {
      backgroundColor: '#264734',
      borderColor: '#264734',
    },
    checkboxTick: {
      width: wp(3.5),
      height: wp(3.5),
      backgroundColor: '#fff',
      borderRadius: wp(1),
    },
    checkboxLabel: {
      fontSize: wp(3.7),
      fontFamily: 'Montserrat-Regular',
      color: '#222',
      flex: 1,
      flexWrap: 'wrap',
    },
    submitButton: {
      backgroundColor: '#264734',
      borderRadius: wp(10),
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
      height: hp(6.5),
      marginTop: hp(2),
      marginBottom: hp(2),
    },
    submitButtonText: {
      color: '#FFF',
      fontSize: wp(4.5),
      fontFamily: 'Poppins-Bold',
    },
    loginRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: hp(1),
      marginBottom: hp(5),
    },
    loginText: {
      fontSize: 14,
      color: '#222',
      fontFamily: 'Poppins-Light',
    },
    loginLink: {
      fontSize: 14,
      color: '#000',
      fontFamily: 'Poppins-Bold',
      textDecorationLine: 'underline',
      marginLeft: wp(1),
    },
  });

export default styles; 