import { StyleSheet } from 'react-native';

const styles = (wp: (val: number) => number, hp: (val: number) => number) => StyleSheet.create({
    bgimg: {
        flex: 1,
        resizeMode: 'cover',
      },
    container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: wp(7),
  },
  header: {
    fontSize: wp(5),
    fontFamily: 'Poppins-Bold',
    color: '#222',
    marginTop: hp(-18),
    marginBottom: hp(5),
    textAlign: 'center',
  },
  iconContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: hp(2),
  },
  successIcon: {
    width: wp(18),
    height: wp(18),
    resizeMode: 'contain',
    marginBottom: hp(1),
  },
  success: {
    fontSize: wp(4.5),
    fontFamily: 'Poppins-Bold',
    color: '#222',
    marginBottom: hp(1),
    textAlign: 'center',
  },
  subText: {
    fontSize: wp(3.2),
    fontFamily: 'Poppins-Regular',
    color: '#B2B2B2',
    marginBottom: hp(1.5),
    marginHorizontal: hp(9),
    textAlign: 'center',
    lineHeight: hp(2),
  },
  date: {
    fontSize: wp(3.5),
    fontFamily: 'Poppins-Medium',
    color: '#264734',
    marginBottom: hp(3),
    textAlign: 'center',
  },
  outlineButton: {
    width: '100%',
    borderWidth: 2,
    borderColor: '#222',
    borderRadius: wp(10),
    paddingVertical: hp(1.4),
    alignItems: 'center',
    marginBottom: hp(1.2),
   
  },
  outlineButtonText: {
    color: '#222',
    fontFamily: 'Poppins-Bold',
    fontSize: wp(4),
  },
  filledButton: {
    width: '100%',
    backgroundColor: '#264734',
    borderRadius: wp(10),
    paddingVertical: hp(1.4),
    alignItems: 'center',
    marginBottom: hp(4),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 3,
  },
  filledButtonText: {
    color: '#fff',
    fontFamily: 'Poppins-Bold',
    fontSize: wp(4),
  },
  bottomRight: {
    position: 'absolute',
    bottom: hp(3),
    right: wp(6),
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarCircle: {
    width: wp(10),
    height: wp(10),
    borderRadius: wp(5),
    backgroundColor: '#264734',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: wp(2),
  },
  avatarText: {
    color: '#fff',
    fontFamily: 'Poppins-Bold',
    fontSize: wp(4),
  },
  bottomText: {
    color: '#222',
    fontFamily: 'Poppins-Regular',
    fontSize: wp(3.3),
  },
  wave: {
    fontSize: wp(3.3),
  },
  outercontainer: {
    position: 'absolute',
    bottom: hp(5),
    right: wp(0),
    flexDirection: 'column',
    alignItems: 'center',
  },
  fab: {
    width: wp(15),
    height: wp(15),
    borderRadius: wp(10),
    backgroundColor: '#003300',
    borderWidth: 1,
    borderColor: '#F97316',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  icon: {
    width: wp(8),
    height: wp(8),
    resizeMode: 'contain',
  },
  textContainer: {
    marginLeft: wp(2),
    paddingHorizontal: wp(3),
    paddingVertical: hp(0.8),
  },
  text: {
    fontSize: wp(3.5),
    color: '#000',
  },
});

export default styles;
